# Generated by Django 6.0.4 on 2026-05-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_admin_polla',
            field=models.BooleanField(default=False, help_text='Permite gestionar afiliados y cargar resultados en la Polla Mundialista.', verbose_name='Admin Polla Mundialista'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comite', 'Comité de Crédito'), ('polla', 'Participante Polla')], default='comite', max_length=10),
        ),
    ]
