# Generated by Django 6.0.4 on 2026-04-28 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='nomina/')),
                ('periodo', models.CharField(help_text='Ej: 2026-04', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('total_empleados', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de Nómina',
                'verbose_name_plural': 'Cargas de Nómina',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('fecha_contrato_hasta', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='nomina.carganomina')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
