# Generated by Django 6.0.4 on 2026-04-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carganomina',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='nomina/'),
        ),
    ]
