# Generated by Django 6.0.4 on 2026-04-30 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cedula', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('proceso', models.CharField(blank=True, max_length=150)),
                ('concepto_prestamo', models.CharField(blank=True, max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_historicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo Histórico',
                'verbose_name_plural': 'Préstamos Históricos',
                'ordering': ['-fecha', 'nombre_completo'],
            },
        ),
    ]
