# Generated by Django 6.0.4 on 2026-04-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_prestamohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncredito',
            name='otras_obligaciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
