# Generated by Django 6.0.4 on 2026-05-16 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPolla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_torneo', models.CharField(default='Copa Mundial FIFA 2026', max_length=100)),
                ('pts_resultado_grupos', models.IntegerField(default=1)),
                ('pts_marcador_grupos', models.IntegerField(default=2)),
                ('pts_resultado_eliminatoria', models.IntegerField(default=2)),
                ('pts_marcador_eliminatoria', models.IntegerField(default=4)),
                ('premio_campeon_sorteo', models.TextField(default='Camiseta original de la Selección Colombia')),
                ('premios_top5_grupos', models.TextField(default='Premios para el Top 5 de la fase de grupos (por definir)')),
                ('premios_top5_general', models.TextField(default='Premios mejorados para el Top 5 general (por definir)')),
                ('fecha_inicio_inscripciones', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre_inscripciones', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre_pronostico_campeon', models.DateTimeField(blank=True, null=True)),
                ('mensaje_no_afiliado', models.TextField(default='¡Afíliate a FONDEINO y participa en la Polla Mundialista! Los nuevos asociados reciben DOBLE POLLA como beneficio de bienvenida.')),
                ('enlace_afiliacion', models.URLField(default='https://www.fondeino.com/')),
                ('polla_cerrada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración de la Polla',
                'verbose_name_plural': 'Configuración de la Polla',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('codigo_fifa', models.CharField(max_length=3, unique=True, verbose_name='Código FIFA')),
                ('bandera_emoji', models.CharField(blank=True, max_length=10, verbose_name='Bandera')),
                ('grupo', models.CharField(max_length=1, verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('area', models.CharField(blank=True, max_length=80, verbose_name='Área')),
                ('cantidad_pollas', models.IntegerField(choices=[(1, 'Una polla'), (2, 'Doble polla')], default=1, verbose_name='Cantidad de pollas')),
                ('motivo_doble_polla', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo asociado'), ('AUMENTO', 'Aumentó aportes')], max_length=10, null=True, verbose_name='Motivo de doble polla')),
                ('acepto_reglamento', models.BooleanField(default=False, verbose_name='Aceptó el reglamento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afiliado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionPolla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_polla', models.IntegerField(choices=[(1, 'Polla A'), (2, 'Polla B')], default=1)),
                ('activa', models.BooleanField(default=True)),
                ('puntos_totales', models.IntegerField(db_index=True, default=0)),
                ('aciertos_resultado', models.IntegerField(default=0)),
                ('aciertos_marcador', models.IntegerField(default=0)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='polla.afiliado')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-puntos_totales', '-aciertos_marcador'],
                'unique_together': {('afiliado', 'numero_polla')},
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número FIFA')),
                ('fase', models.CharField(choices=[('GRUPOS', 'Fase de grupos'), ('TREINTA_DOS', 'Ronda de 32'), ('OCTAVOS', 'Octavos de final'), ('CUARTOS', 'Cuartos de final'), ('SEMIS', 'Semifinales'), ('TERCERO', 'Tercer puesto'), ('FINAL', 'Final')], max_length=12, verbose_name='Fase')),
                ('jornada', models.IntegerField(blank=True, null=True, verbose_name='Jornada')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora (Colombia)')),
                ('estadio', models.CharField(blank=True, max_length=100, verbose_name='Estadio')),
                ('ciudad', models.CharField(blank=True, max_length=60, verbose_name='Ciudad')),
                ('goles_local', models.IntegerField(blank=True, null=True, verbose_name='Goles local')),
                ('goles_visitante', models.IntegerField(blank=True, null=True, verbose_name='Goles visitante')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='polla.equipo', verbose_name='Local')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='polla.equipo', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha_hora', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PronosticoCampeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acerto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polla.equipo', verbose_name='Equipo campeón')),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pronostico_campeon', to='polla.inscripcionpolla')),
            ],
            options={
                'verbose_name': 'Pronóstico Campeón',
                'verbose_name_plural': 'Pronósticos Campeón',
            },
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.IntegerField(verbose_name='Goles local')),
                ('goles_visitante', models.IntegerField(verbose_name='Goles visitante')),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('acerto_resultado', models.BooleanField(default=False)),
                ('acerto_marcador', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='polla.inscripcionpolla')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='polla.partido')),
            ],
            options={
                'verbose_name': 'Pronóstico',
                'verbose_name_plural': 'Pronósticos',
                'unique_together': {('inscripcion', 'partido')},
            },
        ),
    ]
