# Generated by Django 5.2.14 on 2026-05-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0005_premios_grupos_ganador_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionpolla',
            name='mensaje_no_afiliado',
            field=models.TextField(default='¡Afíliate a FONDEINO y participa en la Polla Mundialista! Valor: $5.000 por asociado.Los nuevos asociados reciben DOBLE POLLA como beneficio promocional.'),
        ),
        migrations.CreateModel(
            name='AutorizacionDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('afiliado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacion_descuento', to='polla.afiliado')),
            ],
            options={
                'verbose_name': 'Autorización de descuento',
                'verbose_name_plural': 'Autorizaciones de descuento',
                'ordering': ['-fecha'],
            },
        ),
    ]
