# Generated by Django 4.2.30 on 2026-05-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0007_actualizar_textos_premios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpolla',
            name='minutos_cierre_pronosticos',
            field=models.IntegerField(default=10, help_text='Los pronósticos se bloquean este número de minutos antes de la hora del partido.', verbose_name='Minutos de cierre antes del partido'),
        ),
    ]
