# Generated by Django 4.2.30 on 2026-05-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0008_add_minutos_cierre_pronosticos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='cantidad_pollas',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='motivo_doble_polla',
        ),
    ]
