# Generated by Django 4.2.30 on 2026-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0009_remove_doble_polla_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpolla',
            name='campeon_habilitado',
            field=models.BooleanField(default=True, help_text='Si está desactivado, nadie puede ingresar ni cambiar el campeón, sin importar la fecha de cierre.', verbose_name='Admitir pronóstico de campeón'),
        ),
    ]
